version: '3.8'

services:
  web:
    build: .
    image: stockforge
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn invproject.asgi:application --host 0.0.0.0 --port 8000 