# Generated by Django 5.1.6 on 2025-03-01 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('raw_components', 'Raw Components'), ('sensor', 'Sensor')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeployedSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('deployment_date', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DEPLOYED', 'Deployed'), ('RETURNED', 'Returned'), ('SOLD', 'Sold')], default='DEPLOYED', max_length=20)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='SensorBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('build_date', models.DateTimeField(auto_now_add=True)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_builds', to='main.inventoryitem')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_builds', to='main.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('Production', 'Production'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Sales', 'Sales'), ('Return', 'Return')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inventoryitem')),
            ],
        ),
    ]
