# Generated by Django 5.1.6 on 2025-03-02 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorbuild',
            name='quantity_used',
        ),
        migrations.RemoveField(
            model_name='sensorbuild',
            name='raw_material',
        ),
        migrations.CreateModel(
            name='SensorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_builds', to='main.inventoryitem')),
                ('sensor_build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='main.sensorbuild')),
            ],
        ),
    ]
