# Generated by Django 5.1.6 on 2025-03-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sensorbuild_quantity_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='part_number',
            field=models.CharField(max_length=50),
        ),
    ]
