# Generated by Django 5.1.6 on 2025-03-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_deployedsensor_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('components', 'Components'), ('built_equipment', 'Built Equipment')], max_length=50),
        ),
    ]
